[build]
  command = "solid-start build"
  functions = "netlify/functions"
  publish = "netlify"

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/

[[redirects]]
  from = "/*"
  to = "https://zensearch.jobs"
  status = 301
  force = true
